# Generated by Django 4.1.7 on 2023-05-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimization',
            name='bar_length',
            field=models.FloatField(default=0),
        ),
    ]
