# Generated by Django 4.1.7 on 2023-05-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizations', '0002_optimization_bar_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OptimizationPart',
        ),
    ]
