# Generated by Django 4.1.7 on 2023-05-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizations', '0003_delete_optimizationpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationbar',
            name='remnant',
            field=models.FloatField(default=0),
        ),
    ]
