# Generated by Django 4.1.7 on 2023-03-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Optimizations',
            fields=[
                ('id', models.AutoField(help_text='ID -> PK, Auto Increment', primary_key=True, serialize=False)),
                ('kerf', models.FloatField(default=0, help_text='Saw Cut Deduction')),
                ('left_deduction', models.FloatField(default=0, help_text='Left bar deduction')),
                ('right_deduction', models.FloatField(default=0, help_text='Right bar deduction')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Request date')),
            ],
            options={
                'verbose_name': 'Optimization',
                'verbose_name_plural': 'Optimizations',
                'db_table': 'optimizations',
            },
        ),
    ]
