# Generated by Django 4.1.7 on 2023-03-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Optimization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optimizations',
            options={'verbose_name': 'Optimization', 'verbose_name_plural': 'Optimizations'},
        ),
    ]
